name: Deploy to Cloudflare Pages

on:
  push:
    branches: [built-output]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        env:
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        run: |
          set -e
          npx wrangler whoami
          npx wrangler pages project list
          npx wrangler pages deploy . --project-name=kvideo --branch=main
